### ISSUE TITLE
Users should be able to add/submit a task within a key press

### ISSUE THREAD

**Issue by MAZ12211** [MAZ12211/undertale-themed-task-app.github.io#1]
Right now the only way to create a task is to type whatever you want in the `input` and press ADD.
https://user-images.githubusercontent.com/80357251/138553973-9618458e-5305-40c5-923b-f97520aeb91f.mp4

Users should also be able to add/submit a task within a keypress. (the Enter key).

**Comment by PiyushIngale007** [comment]
Can i work on this issue?

**Comment by MAZ12211** [comment]
> Can i work on this issue?

Sure. go ahead!
